configfile: "config.yaml"
NORMAL = config["sample_normal"]
TUMOR = config["sample_tumor"]
RNUMBER = "r1031919"
rule all:
    input:
        "TLE66_N.fastq",
        "TLE66_T.fastq",
        "50.annotated/annotated_snps.vcf",
        "00.logs/upload_annotated_vcf_to_mango.done"
rule download_normal_fastq_from_mango:
    output:
        "TLE66_N.fastq"
    shell:
        "iron download /gbiomed/home/large_omics_course/fastq/TLE66_N.fastq ./ && test -s TLE66_N.fastq"
rule download_tumor_fastq_from_mango:
    output:
        "TLE66_T.fastq"
    shell:
        "iron download /gbiomed/home/large_omics_course/fastq/TLE66_T.fastq ./ && test -s TLE66_T.fastq"
rule copy_existing_annotated_vcf:
    input:
        "/data/leuven/386/vsc38681/variant_calling_manual/final_results/annotated_snps.vcf"
    output:
        "50.annotated/annotated_snps.vcf"
    shell:
        "mkdir -p 50.annotated && cp {input} {output} && test -s {output}"
rule upload_annotated_vcf_to_mango:
    input:
        "50.annotated/annotated_snps.vcf"
    output:
        touch("00.logs/upload_annotated_vcf_to_mango.done")
    shell:
        "mkdir -p 00.logs; iron mkdir /gbiomed/home/large_omics_course/output/r1031919 || true; iron upload {input} /gbiomed/home/large_omics_course/output/r1031919/; touch {output}"
